/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Date;
import javax.swing.JOptionPane;
import logica.usuarioLogica;
import modelo.Indicador;
import modelo.Iniciativa;
import modelo.Meta;
import modelo.Objetivo;

/**
 *
 * @author Usuario
 */
public class definirObjetivo extends javax.swing.JPanel {

    private usuarioLogica usuarioL = new usuarioLogica();
    
    public definirObjetivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        meta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        iniciativa = new javax.swing.JTextField();
        indicador = new javax.swing.JTextField();
        definir = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Definicion de los objetivos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 261, 27));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Meta");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, 40));
        add(meta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Codigo objetivo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 210, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Iniciativa");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Indicador");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, 40));
        add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, 40));
        add(iniciativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 240, 40));
        add(indicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 240, 40));

        definir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        definir.setText("Definir");
        definir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirActionPerformed(evt);
            }
        });
        add(definir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void definirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirActionPerformed
        if(codigo.getText().equals("") || iniciativa.getText().equals("") || indicador.getText().equals("") || meta.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Llene todos los campos por favor");       
        }
        else{
            Date fechaRealizacion = new Date(2019, 8, 29);
            
            Objetivo o = new Objetivo();
            Iniciativa i = new Iniciativa();
            Indicador ind = new Indicador();
            Meta m = new Meta();
            
            o.setCodigoObjetivo(codigo.getText());
            o.setFecha(fechaRealizacion);
            o.setPerspectiva("Cliente");
            o.setCreadorObjetivo(usuarioL.encontrar("1116280600"));
            
            i.setDescripcionIniciativa(iniciativa.getText());
            i.setFechaIniciativa(fechaRealizacion);
            
            ind.setDescripcionIndicador(indicador.getText());
            ind.setFechaIndicador(fechaRealizacion);
            
            m.setDescripcionMeta(meta.getText());
            m.setFechaMeta(fechaRealizacion);
        }
    }//GEN-LAST:event_definirActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new definirObjetivo.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton definir;
    private javax.swing.JTextField indicador;
    private javax.swing.JTextField iniciativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField meta;
    // End of variables declaration//GEN-END:variables
}
