/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import javax.swing.JOptionPane;
import logica.usuarioLogica;
import modelo.Usuario;


/**
 *
 * @author Usuario
 */
public class login extends javax.swing.JFrame {
    
    private usuarioLogica usuarioL = new usuarioLogica();
    private List<Usuario> usuarios;
    
    public login() {
        super("Sistema de consolidacion de objetivos");
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        identificacionUsuario = new javax.swing.JTextField();
        claveUsuario = new javax.swing.JTextField();
        ingresarLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setText("Bienvenido al sistema de consolidacion de objetivos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 500, 46));

        identificacionUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        identificacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(identificacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 263, 40));

        claveUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        claveUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(claveUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 263, 40));

        ingresarLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ingresarLogin.setText("Ingresar");
        ingresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("                 Identificación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("                   Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 40));

        salir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 110, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identificacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionUsuarioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void ingresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarLoginActionPerformed
        usuarios = usuarioL.consultar();
        boolean bool = true;
                
        for(Usuario u: usuarios){
            if(identificacionUsuario.getText().equals(u.getCedula()) && claveUsuario.getText().equals(u.getClave()) && u.getTipoUsuario().equals("Administrador")){
               funcionAdministrador funciones = new funcionAdministrador();
               funciones.setVisible(true);
               dispose();
               bool = false;
               break;
            }
            
            else if(identificacionUsuario.getText().equals(u.getCedula()) && claveUsuario.getText().equals(u.getClave()) && u.getTipoUsuario().equals("Perspectiva cliente")){
               principal interfazPrincipal = new principal();
               interfazPrincipal.setVisible(true);
               dispose();
               bool = false;
               break;
            }
            
            else if(identificacionUsuario.getText().equals(u.getCedula()) && claveUsuario.getText().equals(u.getClave()) && u.getTipoUsuario().equals("Perspectiva financiera")){
               principal interfazPrincipal = new principal();
               interfazPrincipal.setVisible(true);
               dispose();
               bool = false;
               break;
            }
            
            else if(identificacionUsuario.getText().equals(u.getCedula()) && claveUsuario.getText().equals(u.getClave()) && u.getTipoUsuario().equals("Perspectiva procesos internos")){
               principal interfazPrincipal = new principal();
               interfazPrincipal.setVisible(true);
               dispose();
               bool = false;
               break;
            }
            
            else if(identificacionUsuario.getText().equals(u.getCedula()) && claveUsuario.getText().equals(u.getClave()) && u.getTipoUsuario().equals("Perspectiva crecimiento y aprendizaje")){
               principal interfazPrincipal = new principal();
               interfazPrincipal.setVisible(true);
               dispose();
               bool = false;
               break;
            }
            
            else if(identificacionUsuario.getText().equals("") || claveUsuario.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Llene todos los campos, por favor");
               identificacionUsuario.setText("");
               claveUsuario.setText("");
            }
            
            else{
                JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrecto");
                identificacionUsuario.setText("");
                claveUsuario.setText("");
            }
        } 
    }//GEN-LAST:event_ingresarLoginActionPerformed

    private void claveUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField claveUsuario;
    private javax.swing.JTextField identificacionUsuario;
    private javax.swing.JButton ingresarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
