/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class secundaria extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public secundaria() {
        super("Balance scorecard");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();

        jLabel11.setText("Procesos internos de la empresa");

        jLabel12.setText("Objetivos");

        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });

        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });

        jLabel13.setText("Indicadores");

        jLabel14.setText("Metas");

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });

        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        jLabel15.setText("Iniciativas");

        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Financiero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 12, 162, 31));

        jLabel2.setText("Objetivos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 91, 87, -1));

        jLabel3.setText("Indicadores");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 91, 87, -1));

        jLabel4.setText("Metas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 91, 87, -1));

        jLabel5.setText("Iniciativas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 91, 87, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 124, 96, 36));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 96, 36));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, 96, 36));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 124, 96, 36));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 172, 96, 36));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 96, 36));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 124, 96, 36));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 172, 96, 36));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 220, 96, 36));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 124, 96, 36));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 172, 96, 36));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 220, 96, 36));

        jLabel6.setText("Procesos internos de la empresa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 12, 267, 31));

        jLabel7.setText("Objetivos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 91, 87, -1));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 124, 96, 36));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 172, 96, 36));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 220, 96, 36));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 220, 96, 36));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 172, 96, 36));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 124, 96, 36));

        jLabel8.setText("Indicadores");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 91, 87, -1));

        jLabel9.setText("Metas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 91, 87, -1));

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 124, 96, 36));

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 172, 96, 36));
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 220, 96, 36));

        jLabel10.setText("Iniciativas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 91, 87, -1));

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 124, 96, 36));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 172, 96, 36));
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 220, 96, 36));

        jLabel16.setText("Clientes");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 354, 162, 31));

        jLabel17.setText("Objetivos");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 433, 87, -1));

        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 466, 96, 36));
        getContentPane().add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 514, 96, 36));
        getContentPane().add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 562, 96, 36));
        getContentPane().add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 562, 96, 36));
        getContentPane().add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 514, 96, 36));

        jTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField42ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 466, 96, 36));

        jLabel18.setText("Indicadores");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 433, 87, -1));

        jLabel19.setText("Metas");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 433, 87, -1));

        jTextField43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField43ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 466, 96, 36));

        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 514, 96, 36));
        getContentPane().add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 562, 96, 36));

        jLabel20.setText("Iniciativas");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 433, 87, -1));

        jTextField46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField46ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 466, 96, 36));
        getContentPane().add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 514, 96, 36));
        getContentPane().add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 562, 96, 36));

        jLabel21.setText("Aprendizaje y crecimiento");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 354, 162, 31));

        jLabel22.setText("Objetivos");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 433, 87, -1));

        jTextField49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField49ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 466, 96, 36));
        getContentPane().add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 514, 96, 36));
        getContentPane().add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 562, 96, 36));
        getContentPane().add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 562, 96, 36));
        getContentPane().add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 514, 96, 36));

        jTextField54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField54ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 466, 96, 36));

        jLabel23.setText("Indicadores");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 433, 87, -1));

        jLabel24.setText("Metas");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 433, 87, -1));

        jTextField55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField55ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 466, 96, 36));

        jTextField56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField56ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField56, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 514, 96, 36));
        getContentPane().add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 562, 96, 36));

        jLabel25.setText("Iniciativas");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 433, 87, -1));

        jTextField58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField58ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField58, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 466, 96, 36));
        getContentPane().add(jTextField59, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 514, 96, 36));
        getContentPane().add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 562, 96, 36));

        jButton1.setText("Agregar objetivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jButton2.setText("Eliminar objetivo");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jButton3.setText("Modificar objetivo");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jButton4.setText("Agregar objetivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jButton5.setText("Eliminar objetivo");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jButton6.setText("Modificar objetivo");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, -1));

        jButton7.setText("Agregar objetivo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jButton8.setText("Eliminar objetivo");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, -1, -1));

        jButton9.setText("Modificar objetivo");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, -1, -1));

        jButton10.setText("Agregar objetivo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, -1, -1));

        jButton11.setText("Eliminar objetivo");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, -1, -1));

        jButton12.setText("Modificar objetivo");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 630, -1, -1));

        jLabel27.setText("Para satisfacer a los clientes, ¿En qué se debe sobresalir?");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 410, 70));

        jLabel28.setText("Para alcanzar los objetivos, ¿Cómo deberíamos ser vistos por los clientes?");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 410, 70));

        jLabel29.setText("Para triunfar financieramente, ¿Cómo debemos aparecer ante nuestros accionistas?");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 410, 70));

        jLabel30.setText("Para alcanzar los objetivos, ¿Cómo mantenar la habilidad de cambiar y progresar?");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 410, 70));

        jButton13.setText("E");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jButton14.setText("A");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jButton15.setText("E");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jButton16.setText("A");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jButton17.setText("A");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jButton18.setText("E");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jButton19.setText("A");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jButton20.setText("E");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jButton21.setText("A");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jButton22.setText("E");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jButton23.setText("A");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jButton24.setText("E");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, -1, -1));

        jButton25.setText("A");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        jButton26.setText("E");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        jButton27.setText("E");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, -1, -1));

        jButton28.setText("A");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, -1, -1));

        jButton29.setText("A");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jButton30.setText("E");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jButton31.setText("A");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, -1, -1));

        jButton32.setText("E");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, -1, -1));

        jButton33.setText("A");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, -1));

        jButton34.setText("E");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, -1));

        jButton35.setText("E");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        jButton36.setText("A");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, -1, -1));

        jButton37.setText("E");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, -1, -1));

        jButton38.setText("A");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        jButton39.setText("E");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, -1, -1));

        jButton40.setText("A");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, -1, -1));

        jButton41.setText("E");
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 600, -1, -1));

        jButton42.setText("A");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, -1, -1));

        jButton43.setText("E");
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, -1, -1));

        jButton44.setText("A");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void jTextField43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField43ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField46ActionPerformed

    private void jTextField49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField49ActionPerformed

    private void jTextField54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField54ActionPerformed

    private void jTextField55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField55ActionPerformed

    private void jTextField56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField56ActionPerformed

    private void jTextField58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField58ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secundaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
